### ISSUE TITLE
Allow users to change passwords

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-transaction-tool-demo#12] opened 2021-07-21 01:21 UTC
### Problem

Users cannot change their passwords after they are created during the initial set-up.

### Solution

Allow users to change their passwords to change passwords on individual keys and the recovery phrase.

- Double click to change the key password from the details screen
- View the recovery phrase in the details screen (after using a password)

**Comment by DSMatusevich** [comment] 2021-07-27 16:34
- Changing keys:
![Screen Shot 2021-07-27 at 11 32 30 AM](https://user-images.githubusercontent.com/42348838/127192429-9bb46b11-67e5-4e21-8a91-cf444a711dd7.png)

![Screen Shot 2021-07-27 at 11 32 52 AM](https://user-images.githubusercontent.com/42348838/127192501-0209e47f-1c9b-4284-8aac-969b37bec4fe.png)

![Screen Shot 2021-07-27 at 11 33 14 AM](https://user-images.githubusercontent.com/42348838/127192564-3c4671f3-8959-471f-8bbf-52c039dbd23f.png)

![Screen Shot 2021-07-27 at 11 33 50 AM](https://user-images.githubusercontent.com/42348838/127192648-135706fe-5154-49af-bfe0-41d90f4b8969.png)

![Screen Shot 2021-07-27 at 11 34 13 AM](https://user-images.githubusercontent.com/42348838/127192723-2cd814bc-67bc-44ec-af78-630be27f0f70.png)

**Comment by DSMatusevich** [comment] 2021-07-27 16:36
@SimiHunjan I left screenshots of the key password changing process. The wording can use some work, but this is essentially the workflow. Any comments?

**Comment by SimiHunjan** [comment] 2021-07-27 23:39
- For creating a new password can we do the UI something similar to this where it says "Password" above the first box and "Confirm Password" above the second box? The character limit can be under the first box as shown as well. And instead of 'Continue' to use 'Reset Password'

![Screen Shot 2021-07-27 at 4 33 10 PM](https://user-images.githubusercontent.com/21989138/127240727-c00e29cb-5501-4b08-90e2-4d25bdd76b1b.png)

- For the last pop-up, we can say "The password for KeyStore-10 has been reset."
- For 'This will change the key's password.' we can use 'This will reset the key's password.'
- The button on the first pop-up change from 'Change Password' to 'Reset Password'

**Comment by DSMatusevich** [comment] 2021-08-09 16:41
- First part of the issue is going in v0.2.0.
- Moving to v0.3.0 for second part

**Closed** 2021-08-12 13:00 UTC
Labels: enhancement
